# GitHub Action for deploying a Next.js app to Namecheap via FTP

name: Deploy to Namecheap

# Triggers the workflow on push events but only for the "main" branch
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Install project dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the Next.js application
      - name: Build application
        run: npm run build

      # 5. Deploy files to server via FTP
      # This action syncs the built files to your Namecheap server.
      # It will upload the .next folder, public folder, node_modules, and necessary config files.
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}
          # The local-dir should be the root of your project
          local-dir: ./
          # Exclude files that are not needed in production
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/!(@next|@radix-ui|@swc|class-variance-authority|clsx|cmdk|date-fns|embla-carousel-react|firebase|framer-motion|geist|lucide-react|next|react-day-picker|react-dom|react-hook-form|react|recharts|sonner|tailwind-merge|tailwindcss-animate|zod)/**
            src/
            .env
            .eslintrc.json
            next.config.ts
            postcss.config.js
            README.md
            tailwind.config.ts
            tsconfig.json

